### ISSUE TITLE
Using "JsonConverter" as root namespace in Json classes

### ISSUE THREAD

**Issue by OlegUfaev** [Handlebars-Net/Handlebars.Net.Helpers#67]
Hi!

First of all, I want to say that I am very grateful for your project. Thank you for doing it.

I encountered a small problem after I updated the "Handlebars.Net.Helpers" package from 2.3.5 to 2.3.12 and got many compilation errors:
> CS0118 'JsonConverter' is a namespace but is used like a type

The point is that my project uses the JsonConverter class (from System.Text.Json) in many places. The problem with this name is because you started using such a namespace: `namespace JsonConverter;` in classes https://github.com/Handlebars-Net/Handlebars.Net.Helpers/tree/master/src/Handlebars.Net.Helpers.Core/Json

I wonder if you could change the namespace for these classes. For example, add `HandlebarsDotNet` or `HandlebarsDotNet.Helpers` in the beginning, like in other classes of your project. Or make them all as internal.

I really hope that my feedback will be helpful.

**Comment by StefH** [comment]
This is indeed introduced in that version.

I copied that implementation from https://github.com/StefH/JsonConverter (probably I need to change the namespace there also in the future if there are issues)

Now now, I'll just change the namespace from the classes here (or make these internal).

**Comment by StefH** [comment]
@OlegUfaev 
Can you try preview version "2.3.13-ci-16977" ?

(https://github.com/Handlebars-Net/Handlebars.Net.Helpers/wiki/MyGet)

**Comment by StefH** [comment]
https://github.com/Handlebars-Net/Handlebars.Net.Helpers/pull/68

**Comment by OlegUfaev** [comment]
@StefH 
I've just tried version "2.3.13-ci-16977". 
Problem solved.

Thank you for your quick response.

**Comment by StefH** [comment]
new nuget will be releases in some time
